-- The restaurant audit (Sean, 2026-10-10: "a simple audit for free and then in the actual guide, we go a bit deeper...
-- just like BCPSMarcomm... scans their page for a set of defined criteria. Look at Google Local, SEO, Web and social").
-- Criteria approved by Sean 2026-10-10. Modeled on the BCPS Marcom audit: weighted items, the score is the distance from a
-- perfect score, every item is Good, Fix or Review.
--
-- ve_audit_criteria: one row per check. in_free marks the ones a visitor's free check runs; the free check shows what is
-- wrong, never why or how (that is the paid Guide). chapter is the Restaurant Guide fix it links to; service is the
-- a la carte service (ve-services) that does it for them, else "Have us do it" is a quote request.
-- ve_audits: one row per run. Written and read only by the ve-restaurant-audit function (no public policies).

create table if not exists public.ve_audit_criteria (
  key text primary key,
  area text not null check (area in ('google', 'seo', 'web', 'social')),
  label text not null,
  weight int not null check (weight > 0),
  in_free boolean not null default false,
  why text not null,
  how text not null,
  chapter text,
  service text,
  sort int not null default 0,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.ve_audits (
  id uuid primary key default gen_random_uuid(),
  tier text not null check (tier in ('free', 'full')),
  listing_id uuid references public.listings(id) on delete set null,
  member_id uuid,
  email text,
  inputs jsonb not null default '{}'::jsonb,
  status text not null default 'running' check (status in ('running', 'done', 'failed')),
  score int,
  max_score int,
  areas jsonb,
  items jsonb,
  facts jsonb,
  error text,
  ip_hash text,
  created_at timestamptz not null default now(),
  finished_at timestamptz
);
create index if not exists ve_audits_listing_idx on public.ve_audits (listing_id, tier, created_at desc);
create index if not exists ve_audits_member_idx on public.ve_audits (member_id, created_at desc);
create index if not exists ve_audits_ip_idx on public.ve_audits (ip_hash, created_at desc);

alter table public.ve_audit_criteria enable row level security;
alter table public.ve_audits enable row level security;

insert into public.ve_audit_criteria (key, area, label, weight, in_free, why, how, chapter, service, sort) values
-- Google Local
('g_found', 'google', 'Your Google Business Profile can be found', 20, true,
 'Most people find a restaurant on Google Maps first. If we cannot find your profile, neither can they.',
 'Search your name and city on Google Maps. If nothing comes up, go to business.google.com, add your restaurant and verify it (Google mails or texts a code). If an old or duplicate profile comes up, claim it there instead of making a new one.',
 'seo', null, 10),
('g_open', 'google', 'Google shows you as open', 10, false,
 'A profile marked closed, temporarily or for good, sends people away even when your doors are open.',
 'In your Business Profile, open Edit profile > Hours and set the business as Open with this week''s hours. If Google marked you closed by mistake, use "Suggest an edit" and then contact Business Profile support.',
 'info', null, 20),
('g_nap', 'google', 'Your name, address and phone match everywhere', 8, false,
 'Google trusts a business more when its name, address and phone match on every site. Mismatches cost you rank and send calls to the wrong number.',
 'Pick one exact version of your name, street address and phone. Put that same version on your Google profile, your website footer, Instagram, Yelp and your Vegans Explore page.',
 'info', null, 30),
('g_hours', 'google', 'Your hours are on Google', 10, true,
 'People check hours before they drive over. Missing hours read as "maybe closed".',
 'Business Profile > Edit profile > Hours. Add regular hours for every day, and special hours for holidays a week ahead.',
 'info', null, 40),
('g_category', 'google', 'Your Google category says what you are', 4, false,
 'Your primary category decides which searches you show up in. "Vegan restaurant" shows up for Vegan searches; a generic category does not.',
 'Business Profile > Edit profile > Business category. Set the primary category to Vegan restaurant (or Vegan bakery, cafe and so on) and add the cuisine as a second category.',
 'seo', null, 50),
('g_photos', 'google', 'Your Google profile has plenty of photos', 6, true,
 'Profiles with lots of real photos get far more clicks and direction requests than ones with a few.',
 'Add at least 10 clear photos: the outside (so people recognize it), the inside, your best dishes and your team. Add new ones every month. Phone photos in daylight are fine.',
 'visuals', 'photo_shoot', 60),
('g_rating', 'google', 'Your Google rating is 4.3 or higher', 6, true,
 'Most diners skip places under about 4 stars, and the rating is the first thing they see.',
 'Reply to every review, kindly and briefly, and fix what the bad ones have in common. Ask happy guests for a review at the table or on the receipt with a QR code to your review link. Never pay for reviews.',
 'feedback', null, 70),
('g_reviews', 'google', 'You have at least 50 Google reviews', 5, false,
 'The number of reviews tells people you are busy and trusted, and it helps you rank.',
 'Get your review link (Business Profile > Ask for reviews) and put it on a table card, the receipt and your thank-you messages. Ask in person when someone says they loved it.',
 'feedback', null, 80),
('g_recent_review', 'google', 'You have a recent Google review', 5, false,
 'Recent reviews show you are open and still good. Only old ones make people wonder.',
 'Ask a few regulars this week for a review, and make asking part of every shift. Reply to each one so new guests see you are listening.',
 'feedback', null, 90),
('g_website', 'google', 'Your Google profile links to your website', 5, false,
 'The website button on Google is how most people get to your menu.',
 'Business Profile > Edit profile > Contact > Website. Add your home page. Add your menu and order links in the same place.',
 'seo', null, 100),
('g_vegan', 'google', 'Google knows you are Vegan', 4, false,
 'People searching "Vegan near me" find places Google knows are Vegan.',
 'Put "Vegan" in your business description and your category, and turn on the Vegan and vegetarian options under More > Offerings. Do not add it to your business name unless it is part of your real name.',
 'branding', null, 110),
-- SEO
('s_title', 'seo', 'Your page title has your name', 4, false,
 'The page title is the blue headline in Google results. Without your name, people do not know it is you.',
 'In your website builder, open SEO settings for the home page and set the title to: Your Name | Vegan Restaurant in Your City.',
 'seo', null, 210),
('s_title_local', 'seo', 'Your site says Vegan and your city', 4, true,
 'Google matches searches like "Vegan restaurant Fort Lauderdale" to pages that say both words.',
 'Put "Vegan" and your city in the home page title and in the main heading, for example "Fort Lauderdale''s 100% Vegan Kitchen".',
 'seo', null, 220),
('s_meta', 'seo', 'Your site has a search description', 4, true,
 'The description is the two lines under your name on Google. Without one, Google picks random text from your page.',
 'In SEO settings, write one or two sentences of about 150 characters: what you serve, that you are Vegan, your neighborhood, and one reason to come.',
 'seo', null, 230),
('s_h1', 'seo', 'Your home page has one main heading', 2, false,
 'One clear main heading tells Google and screen readers what the page is about.',
 'Make your main headline the page''s only Heading 1, and use Heading 2 for the sections under it. Most builders have a text style menu for this.',
 'seo', null, 240),
('s_schema', 'seo', 'Your site tells Google your restaurant details', 6, false,
 'Restaurant markup gives Google your hours, address, menu and price range directly, which can show them right in search results.',
 'Turn on the restaurant or local business setting in your builder (Squarespace, Wix and Toast sites have one), or add Restaurant schema to the home page with your name, address, phone, hours, menu link and cuisine "Vegan".',
 'seo', null, 250),
('s_indexable', 'seo', 'Google is allowed to list your site', 8, false,
 'A site set to "hide from search engines" never shows up on Google, however good it is.',
 'In your builder''s SEO settings, make sure "hide from search engines" is off, and that robots.txt does not block the whole site. Then add the site in Google Search Console.',
 'seo', null, 260),
('s_sitemap', 'seo', 'Your site has a sitemap', 2, false,
 'A sitemap helps Google find every page, including your menu.',
 'Most builders make one at /sitemap.xml automatically. Submit it in Google Search Console.',
 'seo', null, 270),
('s_alt', 'seo', 'Your photos are described', 3, false,
 'Photo descriptions (alt text) help you show up in image search and let people using screen readers know what is on the plate.',
 'Give each photo a short description of what is in it, for example "Jackfruit tacos with mango salsa".',
 'seo', null, 280),
('s_menu_text', 'seo', 'Your menu is a real page, not only a PDF or picture', 5, false,
 'Google cannot read a menu inside a picture, and a PDF is hard to use on a phone. A text menu gets found for dish searches like "Vegan mac and cheese".',
 'Make a Menu page with each dish typed out, its price and a short description. Keep the PDF as a download if you like.',
 'menu', null, 290),
('s_psi_seo', 'seo', 'Google''s SEO check passes', 3, false,
 'Google''s own check finds basic problems that keep a page from ranking.',
 'Run your site through pagespeed.web.dev and open the SEO section. Fix each item it lists; most are a setting in your builder.',
 'seo', null, 300),
-- Web
('w_found', 'web', 'You have a website that opens', 15, true,
 'Without a website, or with one that does not load, you depend on apps that take a cut and own your customers.',
 'If you have no site, a simple one on Squarespace, Wix or your ordering system is enough: home, menu, hours and location, order. If it does not load, check with your host that the domain and plan are paid and the address is right.',
 'info', null, 410),
('w_https', 'web', 'Your site is secure (https)', 6, false,
 'Browsers warn people away from sites without https, and Google ranks them lower.',
 'Turn on SSL in your builder or host (it is free on almost all of them) and set the site to always use https.',
 'info', null, 420),
('w_mobile', 'web', 'Your site works on phones', 5, false,
 'Most people look you up on their phone. A site that does not fit the screen loses them.',
 'Use a mobile-friendly template and check every page on your own phone. The page needs a mobile viewport setting, which modern builders add for you.',
 'info', null, 430),
('w_speed', 'web', 'Your site loads fast on a phone', 6, true,
 'Every extra second on a phone loses visitors, and Google ranks slow sites lower.',
 'Shrink big photos before uploading (under 300 KB each), remove sliders and autoplay videos from the home page, and remove apps or plugins you do not use. Check again at pagespeed.web.dev.',
 'info', null, 440),
('w_a11y', 'web', 'Your site is easy for everyone to use', 4, false,
 'An accessible site works for guests with low vision or who use screen readers, and it is easier for everyone.',
 'Run pagespeed.web.dev and open Accessibility. Fix low-contrast text, buttons without labels and photos without descriptions first.',
 'info', null, 450),
('w_contact', 'web', 'Your phone and address are on your home page', 5, false,
 'People should not have to hunt to call you or find you.',
 'Put your phone (as a tap-to-call link) and your address (linked to Google Maps) in the header or footer of every page.',
 'info', null, 460),
('w_hours', 'web', 'Your hours are on your website', 4, false,
 'Hours are the most looked-for thing on a restaurant site.',
 'Add your hours to the home page or footer, and update them the same day you change them on Google.',
 'info', null, 470),
('w_order', 'web', 'People can order or book from your site', 4, false,
 'A visitor ready to eat should be one tap from ordering or booking.',
 'Add an Order online button (your own ordering first, then delivery apps) and a Reserve button if you take bookings, at the top of the home page.',
 'info', null, 480),
('w_links', 'web', 'Your main links work', 3, false,
 'A broken menu or order link is a lost customer.',
 'Click every link in your menu bar and footer once a month. Fix or remove any that show "page not found".',
 'info', null, 490),
('w_fresh', 'web', 'Your site looks up to date', 2, false,
 'An old copyright year or last year''s specials make people wonder if you are still open.',
 'Update the footer year, remove old events and specials, and add something new each month.',
 'info', null, 500),
-- Social
('x_ig_found', 'social', 'You have an Instagram we can find', 10, true,
 'Instagram is where Vegan diners look at the food before they come.',
 'Make a business Instagram account in your restaurant''s name, and link it from your website and Google profile so people find the right one.',
 'social', null, 610),
('x_ig_linked', 'social', 'Your website links to your Instagram', 3, false,
 'A link from your site proves which account is really yours.',
 'Add your Instagram icon to your website header or footer.',
 'social', null, 620),
('x_ig_recent', 'social', 'You posted on Instagram in the last 14 days', 8, true,
 'An account that has gone quiet looks closed.',
 'Post at least once a week: a dish, a special, your team, a guest''s photo (with permission). Plan a month of posts in one sitting.',
 'social', 'social_post', 630),
('x_ig_freq', 'social', 'You post on Instagram every week', 4, false,
 'Posting often keeps you in people''s feeds and reminds them to come back.',
 'Aim for two posts and a few stories a week. Short videos of food being made do best. Reuse what works.',
 'social', 'reel', 640),
('x_ig_bio', 'social', 'Your Instagram bio has your city and a link', 3, false,
 'Your bio is your sign: what you are, where you are, and where to order.',
 'Put "Vegan", your neighborhood or city, and your hours or a short line in the bio, and a link to your menu or order page.',
 'social', null, 650),
('x_fb', 'social', 'You have a Facebook page', 3, false,
 'Many locals, especially older guests and groups planning events, still check Facebook.',
 'Make a Facebook page for the restaurant with your hours, menu link and photos. You can share your Instagram posts to it automatically.',
 'social', null, 660),
('x_tiktok', 'social', 'You are on TikTok', 2, false,
 'TikTok sends new, younger diners to restaurants through short food videos.',
 'Make a TikTok in your restaurant''s name and post the same short videos you make for Instagram.',
 'social', 'reel', 670),
('x_handles', 'social', 'Your social names match', 2, false,
 'Matching names make you easy to find and tag.',
 'Use the same handle on Instagram, TikTok and Facebook where you can, and list them on your website.',
 'social', null, 680),
('x_hours_agree', 'social', 'Your hours agree on Google and your website', 3, false,
 'Different hours in different places make people distrust all of them.',
 'Choose one set of hours and update Google, your website, Instagram and your Vegans Explore page the same day.',
 'info', null, 690)
on conflict (key) do update set area = excluded.area, label = excluded.label, weight = excluded.weight, in_free = excluded.in_free,
  why = excluded.why, how = excluded.how, chapter = excluded.chapter, service = excluded.service, sort = excluded.sort, updated_at = now();
